import { test, expect, type Page } from '@playwright/test';
import { resolve } from 'node:path';
import { copyFile } from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';

async function boot(page: Page, scenario: string) {
  await page.addInitScript({ path: resolve('tests/frontend/tauri-fixture-init.js') });
  await page.goto(`/?scenario=${scenario}`);
  await expect(page.locator('.boot')).toHaveCount(0);
}
async function step(page: Page, name: string) {
  await page.getByRole('navigation', { name: '작업 단계' }).getByRole('button', { name: new RegExp(`^${name}`) }).click();
}
async function run(page: Page) {
  await step(page, '번역 준비');
  const start = page.getByRole('button', { name: /^(번역 시작|이어서 번역)$/ });
  await start.click();
}

// Stable gate names must be regenerated by the current run, not left as stale artifacts.
const gateScreens: Record<string, string> = {
  empty: '01-world-empty', selected: '02-world-selected',
  'scan-running': '03-scan-running', scanned: '04-scan-complete',
  run: '07-run-confirm', 'run-progress': '08-run-progress',
  'result-success': '09-result-success', 'result-failed': '10-result-failed',
  '백업 관리': '11-backups', '환경 설정': '12-settings', '정보': '13-about',
  'dark-review': '14-dark-review'
};
async function gateScreenshot(page: Page, name: string, source: string) {
  // Reuse this run's capture; never copy a stale artifact or render the same frame twice.
  await copyFile(source, `output/playwright/${gateScreens[name]}.png`);
}

test('manual browser preview uses synthetic candidates without provider requests', async ({ page }) => {
  const externalRequests: string[] = [];
  page.on('request', (request) => {
    if (/^https?:/.test(request.url()) && new URL(request.url()).hostname !== '127.0.0.1') externalRequests.push(request.url());
  });
  await page.goto('/tests/frontend/preview.html?scenario=review');
  await step(page, '번역할 문장 고르기');
  await expect(page.locator('tr[data-index="0"]')).toContainText('Welcome to Roguefire');
  await page.locator('tr[data-index="0"]').click();
  await expect(page.locator('#manual-translation')).toBeVisible();
  expect(externalRequests).toEqual([]);
});

test('review overview and selected detail have full usable editor width', async ({ page }) => {
  await boot(page, 'review');
  await step(page, '번역할 문장 고르기');
  await expect(page.locator('tr[data-index="0"]')).toBeVisible();
  await page.screenshot({ path: 'output/playwright/05-review.png', fullPage: true });
  await page.locator('tr[data-index="0"]').click();
  await expect(page.locator('#manual-translation')).toBeVisible();
  expect(await page.locator('#manual-translation').evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(250);
  await page.screenshot({ path: 'output/playwright/06-review-selected.png', fullPage: true });
});

test('translation report export contains the displayed result', async ({ page }) => {
  await boot(page, 'result-success');
  await run(page);
  await expect(page.getByRole('heading', { name: '번역 결과', exact: true })).toBeVisible();
  const downloading = page.waitForEvent('download');
  await page.getByRole('button', { name: '최신 번역 보고서 내보내기', exact: true }).click();
  const download = await downloading;
  expect(download.suggestedFilename()).toBe('translate-report.json');
});

test('result to backup restore returns to a valid scan step', async ({ page }) => {
  await boot(page, 'result-success');
  await run(page);
  await expect(page.getByRole('heading', { name: '번역 결과', exact: true })).toBeVisible();
  await expect(page.getByText('번역을 성공적으로 마쳤습니다', { exact: true })).toBeVisible();
  expect(await page.locator('main').innerText()).not.toMatch(/\bcompleted\b|translation_batch_start/);
  await page.getByRole('button', { name: '백업 관리', exact: true }).click();
  await page.getByRole('button', { name: '이 시점으로 월드 복원' }).first().click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: '이 시점으로 월드 복원' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  // The backup page says the reviewed scan is gone and offers the way to scan again.
  const notice = page.getByRole('status').filter({ hasText: '번역하려면 다시 스캔하세요' });
  await expect(notice).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: 'output/playwright/restore-rescan-notice.png' });
  await notice.getByRole('button', { name: '월드 스캔으로' }).click();
  await expect(page.getByRole('heading', { name: '번역할 문장 찾기', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '번역 결과', exact: true })).toHaveCount(0);
  await expect(page.getByRole('status').filter({ hasText: '이전 스캔·검토 결과를 지웠습니다' })).toBeVisible();
  await page.getByRole('button', { name: '스캔 시작', exact: true }).click();
  await expect(page.getByText('번역하려면 다시 스캔하세요')).toHaveCount(0);
});

for (const scenario of ['result-success']) {
  test(`${scenario} is localized and accessible`, async ({ page }) => {
    await boot(page, scenario);
    await run(page);
    await expect(page.getByRole('heading', { name: '번역 결과', exact: true })).toBeVisible();
    const issues = await new AxeBuilder({ page }).analyze();
    expect(issues.violations).toEqual([]);
    await page.screenshot({ path: `output/playwright/${scenario}.png`, fullPage: true });
    await gateScreenshot(page, scenario, `output/playwright/${scenario}.png`);
  });
}

const resultCases = [
  { scenario: 'result-needs_retry', title: '번역이 완료되지 않아 작업을 중단했습니다', body: '월드 파일은 변경되지 않았습니다.', action: '실패한 6개만 다시 번역', stat: '번역문 준비' },
  { scenario: 'result-partial', title: '일부 텍스트만 번역되었습니다', body: '번역되지 않은 문장은 원문 그대로 유지되었습니다. 아래 상세 내역을 확인해 주세요.', action: '실패한 2개만 다시 번역', stat: '월드에 적용됨' },
  { scenario: 'result-failed', title: '번역에 실패했습니다', body: '번역을 완료하지 못했습니다. 월드 파일은 바뀌지 않았습니다.', action: '실패한 6개만 다시 번역', stat: '번역문 준비' },
  { scenario: 'result-cancelled', title: '번역을 취소했습니다', body: '이미 번역된 문장은 안전하게 저장되어 있어 언제든 이어서 진행할 수 있습니다.', action: '남은 문장만 이어서 시도', stat: '번역문 준비' },
  { scenario: 'result-invalidated', title: '스캔 이후 월드 파일이 변경되었습니다', body: '데이터 무결성 보호를 위해 저장을 중단했습니다. 월드를 다시 스캔해 주세요.', action: '처음부터 다시 스캔', stat: '번역문 준비' },
  { scenario: 'result-unsupported', title: '지원하지 않는 월드 형식입니다', body: '월드 파일은 전혀 변경되지 않았습니다.', action: '처음부터 다시 스캔', stat: '번역문 준비' }
];

for (const { scenario, title, body, action, stat } of resultCases) {
  test(`${scenario} explains the outcome and offers the matching next action`, async ({ page }) => {
    await boot(page, scenario);
    await run(page);
    await expect(page.getByRole('heading', { name: '번역 결과', exact: true })).toBeVisible();
    await expect(page.getByRole('status').filter({ hasText: title })).toContainText(body);
    await expect(page.getByRole('button', { name: action, exact: true })).toBeVisible();
    expect(await page.locator('main').innerText()).not.toMatch(/\b(partial|failed|cancelled|invalidated|unsupported)\b/);
    // "Applied" only when the world was written; otherwise the same rows are "prepared" (U9).
    await expect(page.getByText(stat, { exact: true })).toBeVisible();
    await expect(page.getByText('번역 완료', { exact: true })).toHaveCount(0);
    if (scenario === 'result-failed') {
      expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
      const source = `output/playwright/${scenario}.png`;
      await page.screenshot({ path: source, fullPage: true });
      await gateScreenshot(page, scenario, source);
    }
  });
}

for (const pageName of ['백업 관리', '환경 설정', '정보']) {
  for (const width of [1440, 840, 320]) {
    test(`${pageName} at ${width}px`, async ({ page }) => {
      await page.setViewportSize({ width, height: 620 });
      await boot(page, 'selected');
      await page.getByRole('button', { name: pageName, exact: true }).click();
      await expect(page.getByRole('heading', { name: pageName === '정보' ? 'PomiTranslate 정보' : pageName, exact: true }).first()).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
      expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
      await page.screenshot({ path: `output/playwright/${pageName}-${width}.png`, fullPage: true });
      if (width === 1440) await gateScreenshot(page, pageName, `output/playwright/${pageName}-${width}.png`);
    });
  }
}

for (const scenario of ['empty', 'selected', 'scan-running', 'scanned', 'run', 'run-progress', 'dark-review']) {
  test(`representative ${scenario} screen`, async ({ page }) => {
    await boot(page, scenario);
    if (scenario === 'selected') await step(page, '월드 고르기');
    if (scenario === 'scan-running') await page.getByRole('button', { name: '스캔 시작', exact: true }).click();
    if (scenario === 'run') await step(page, '번역 준비');
    if (scenario === 'run-progress') await run(page);
    if (scenario === 'dark-review') await step(page, '번역할 문장 고르기');
    if (scenario === 'scan-running' || scenario === 'run-progress') {
      await expect(page.getByRole('progressbar')).toBeVisible();
      expect(await page.locator('main').innerText()).not.toMatch(/translation_batch_start|phase_start|file_start/);
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await page.screenshot({ path: `output/playwright/${scenario}.png`, fullPage: true });
    await gateScreenshot(page, scenario, `output/playwright/${scenario}.png`);
  });
}


test('sidebar elapsed time ticks while waiting for an in-flight request', async ({ page }) => {
  await boot(page, 'run-progress');
  await run(page);
  await expect(page.locator('.sidebar .sub')).not.toHaveText('0초', { timeout: 4000 });
  expect(await page.locator('main').innerText()).not.toMatch(/translation_batch_start|phase_start/);
});


test('OpenRouter reasoning separates mode and supported effort and persists choices', async ({ page }) => {
  await boot(page, 'selected&model=deepseek/deepseek-v4.1-flash');
  await page.getByRole('button', { name: '환경 설정', exact: true }).click();
  await expect(page.getByText('모델 기본값: 켜짐 · 강하게 (high)', { exact: true })).toBeVisible();
  await expect(page.getByRole('radio', { name: '모델 기본값', exact: true })).toBeChecked();
  await expect(page.locator('#openrouter-reasoning')).toHaveCount(0);
  await page.getByRole('radio', { name: '직접 설정', exact: true }).check();
  const select = page.locator('#openrouter-reasoning');
  await expect(select.locator('option')).toHaveText(['가볍게 (low)', '강하게 (high)', '최대 (max)']);
  await select.selectOption('max');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await expect(select).toHaveValue('max');
  await expect(page.locator('.save-bar')).toHaveCount(0);
  await page.getByRole('button', { name: '정보', exact: true }).click();
  await page.getByRole('button', { name: '환경 설정', exact: true }).click();
  await expect(select).toHaveValue('max');
  await page.locator('#model').fill('mandatory-fixture');
  await expect(page.getByRole('radio', { name: '추론 끄기', exact: true })).toBeDisabled();
  await expect(page.getByText('이 모델은 추론을 끌 수 없습니다.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '저장', exact: true })).toBeDisabled();
  await page.getByRole('radio', { name: '모델 기본값', exact: true }).check();
  await page.locator('#model').fill('xiaomi/mimo-v2.6-flash');
  await expect(page.getByRole('radio', { name: '직접 설정', exact: true })).toBeDisabled();
});

for (const width of [1440, 840, 320]) {
  test(`sidebar stays fixed while settings scroll at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 620 });
    await boot(page, 'selected');
    await page.getByRole('button', { name: '환경 설정', exact: true }).click();
    const sidebar = page.locator('.sidebar');
    const before = await sidebar.boundingBox();
    await page.locator('main').evaluate((pane) => pane.scrollTo(0, pane.scrollHeight));
    const after = await sidebar.boundingBox();
    expect(after?.y).toBeCloseTo(before!.y, 0);
    expect(after?.height).toBeCloseTo(before!.height, 0);
    await expect(page.getByRole('button', { name: '번역 작업', exact: true })).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `output/playwright/fixed-sidebar-${width}.png` });
  });
}
